/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComoPagarRouteImport } from './routes/como-pagar'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SuperOfertasRouteImport } from './routes/super-ofertas'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TrocasDevolucoesRouteImport } from './routes/trocas-devolucoes'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminEquipaRouteImport } from './routes/admin.equipa'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminLogisticaRouteImport } from './routes/admin.logistica'
import { Route as AdminLojasRouteImport } from './routes/admin.lojas'
import { Route as AdminMetasRouteImport } from './routes/admin.metas'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminReceitaRouteImport } from './routes/admin.receita'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ApiEmailRouteImport } from './routes/api/email'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PayMethodRouteImport } from './routes/pay.$method'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as AdminAbasIdRouteImport } from './routes/admin.abas.$id'
import { Route as AdminLojasIdRouteImport } from './routes/admin.lojas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoPagarRoute = ComoPagarRouteImport.update({
  id: '/como-pagar',
  path: '/como-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperOfertasRoute = SuperOfertasRouteImport.update({
  id: '/super-ofertas',
  path: '/super-ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasDevolucoesRoute = TrocasDevolucoesRouteImport.update({
  id: '/trocas-devolucoes',
  path: '/trocas-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipaRoute = AdminEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticaRoute = AdminLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetasRoute = AdminMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitaRoute = AdminReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ApiEmailRoute = ApiEmailRouteImport.update({
  id: '/api/email',
  path: '/api/email',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PayMethodRoute = PayMethodRouteImport.update({
  id: '/pay/$method',
  path: '/pay/$method',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbasIdRoute = AdminAbasIdRouteImport.update({
  id: '/abas/$id',
  path: '/abas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasIdRoute = AdminLojasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLojasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/como-pagar': typeof ComoPagarRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/super-ofertas': typeof SuperOfertasRoute
  '/support': typeof SupportRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/wallet': typeof WalletRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/equipa': typeof AdminEquipaRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/lojas': typeof AdminLojasRouteWithChildren
  '/admin/metas': typeof AdminMetasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/email': typeof ApiEmailRoute
  '/category/$slug': typeof CategorySlugRoute
  '/pay/$method': typeof PayMethodRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/abas/$id': typeof AdminAbasIdRoute
  '/admin/lojas/$id': typeof AdminLojasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/como-pagar': typeof ComoPagarRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/super-ofertas': typeof SuperOfertasRoute
  '/support': typeof SupportRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/wallet': typeof WalletRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/equipa': typeof AdminEquipaRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/lojas': typeof AdminLojasRouteWithChildren
  '/admin/metas': typeof AdminMetasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/email': typeof ApiEmailRoute
  '/category/$slug': typeof CategorySlugRoute
  '/pay/$method': typeof PayMethodRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/abas/$id': typeof AdminAbasIdRoute
  '/admin/lojas/$id': typeof AdminLojasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/como-pagar': typeof ComoPagarRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/super-ofertas': typeof SuperOfertasRoute
  '/support': typeof SupportRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/wallet': typeof WalletRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/equipa': typeof AdminEquipaRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/lojas': typeof AdminLojasRouteWithChildren
  '/admin/metas': typeof AdminMetasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/receita': typeof AdminReceitaRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/api/email': typeof ApiEmailRoute
  '/category/$slug': typeof CategorySlugRoute
  '/pay/$method': typeof PayMethodRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/abas/$id': typeof AdminAbasIdRoute
  '/admin/lojas/$id': typeof AdminLojasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/como-pagar'
    | '/coupons'
    | '/favorites'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/points'
    | '/privacidade'
    | '/settings'
    | '/store'
    | '/super-ofertas'
    | '/support'
    | '/termos'
    | '/trocas-devolucoes'
    | '/wallet'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/cupons'
    | '/admin/equipa'
    | '/admin/home'
    | '/admin/logistica'
    | '/admin/lojas'
    | '/admin/metas'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/receita'
    | '/admin/usuarios'
    | '/api/email'
    | '/category/$slug'
    | '/pay/$method'
    | '/product/$id'
    | '/shop/$id'
    | '/admin/'
    | '/admin/abas/$id'
    | '/admin/lojas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/como-pagar'
    | '/coupons'
    | '/favorites'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/points'
    | '/privacidade'
    | '/settings'
    | '/store'
    | '/super-ofertas'
    | '/support'
    | '/termos'
    | '/trocas-devolucoes'
    | '/wallet'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/cupons'
    | '/admin/equipa'
    | '/admin/home'
    | '/admin/logistica'
    | '/admin/lojas'
    | '/admin/metas'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/receita'
    | '/admin/usuarios'
    | '/api/email'
    | '/category/$slug'
    | '/pay/$method'
    | '/product/$id'
    | '/shop/$id'
    | '/admin'
    | '/admin/abas/$id'
    | '/admin/lojas/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/como-pagar'
    | '/coupons'
    | '/favorites'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/points'
    | '/privacidade'
    | '/settings'
    | '/store'
    | '/super-ofertas'
    | '/support'
    | '/termos'
    | '/trocas-devolucoes'
    | '/wallet'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/cupons'
    | '/admin/equipa'
    | '/admin/home'
    | '/admin/logistica'
    | '/admin/lojas'
    | '/admin/metas'
    | '/admin/pagamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/receita'
    | '/admin/usuarios'
    | '/api/email'
    | '/category/$slug'
    | '/pay/$method'
    | '/product/$id'
    | '/shop/$id'
    | '/admin/'
    | '/admin/abas/$id'
    | '/admin/lojas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoPagarRoute: typeof ComoPagarRoute
  CouponsRoute: typeof CouponsRoute
  FavoritesRoute: typeof FavoritesRoute
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PointsRoute: typeof PointsRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRoute
  SuperOfertasRoute: typeof SuperOfertasRoute
  SupportRoute: typeof SupportRoute
  TermosRoute: typeof TermosRoute
  TrocasDevolucoesRoute: typeof TrocasDevolucoesRoute
  WalletRoute: typeof WalletRoute
  ApiEmailRoute: typeof ApiEmailRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PayMethodRoute: typeof PayMethodRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopIdRoute: typeof ShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-pagar': {
      id: '/como-pagar'
      path: '/como-pagar'
      fullPath: '/como-pagar'
      preLoaderRoute: typeof ComoPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-ofertas': {
      id: '/super-ofertas'
      path: '/super-ofertas'
      fullPath: '/super-ofertas'
      preLoaderRoute: typeof SuperOfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-devolucoes': {
      id: '/trocas-devolucoes'
      path: '/trocas-devolucoes'
      fullPath: '/trocas-devolucoes'
      preLoaderRoute: typeof TrocasDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipa': {
      id: '/admin/equipa'
      path: '/equipa'
      fullPath: '/admin/equipa'
      preLoaderRoute: typeof AdminEquipaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistica': {
      id: '/admin/logistica'
      path: '/logistica'
      fullPath: '/admin/logistica'
      preLoaderRoute: typeof AdminLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metas': {
      id: '/admin/metas'
      path: '/metas'
      fullPath: '/admin/metas'
      preLoaderRoute: typeof AdminMetasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receita': {
      id: '/admin/receita'
      path: '/receita'
      fullPath: '/admin/receita'
      preLoaderRoute: typeof AdminReceitaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/email': {
      id: '/api/email'
      path: '/api/email'
      fullPath: '/api/email'
      preLoaderRoute: typeof ApiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$method': {
      id: '/pay/$method'
      path: '/pay/$method'
      fullPath: '/pay/$method'
      preLoaderRoute: typeof PayMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/abas/$id': {
      id: '/admin/abas/$id'
      path: '/abas/$id'
      fullPath: '/admin/abas/$id'
      preLoaderRoute: typeof AdminAbasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/$id': {
      id: '/admin/lojas/$id'
      path: '/$id'
      fullPath: '/admin/lojas/$id'
      preLoaderRoute: typeof AdminLojasIdRouteImport
      parentRoute: typeof AdminLojasRoute
    }
  }
}

interface AdminLojasRouteChildren {
  AdminLojasIdRoute: typeof AdminLojasIdRoute
}

const AdminLojasRouteChildren: AdminLojasRouteChildren = {
  AdminLojasIdRoute: AdminLojasIdRoute,
}

const AdminLojasRouteWithChildren = AdminLojasRoute._addFileChildren(
  AdminLojasRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminEquipaRoute: typeof AdminEquipaRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLogisticaRoute: typeof AdminLogisticaRoute
  AdminLojasRoute: typeof AdminLojasRouteWithChildren
  AdminMetasRoute: typeof AdminMetasRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminReceitaRoute: typeof AdminReceitaRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAbasIdRoute: typeof AdminAbasIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminEquipaRoute: AdminEquipaRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLogisticaRoute: AdminLogisticaRoute,
  AdminLojasRoute: AdminLojasRouteWithChildren,
  AdminMetasRoute: AdminMetasRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminReceitaRoute: AdminReceitaRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAbasIdRoute: AdminAbasIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ComoPagarRoute: ComoPagarRoute,
  CouponsRoute: CouponsRoute,
  FavoritesRoute: FavoritesRoute,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PointsRoute: PointsRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRoute,
  SuperOfertasRoute: SuperOfertasRoute,
  SupportRoute: SupportRoute,
  TermosRoute: TermosRoute,
  TrocasDevolucoesRoute: TrocasDevolucoesRoute,
  WalletRoute: WalletRoute,
  ApiEmailRoute: ApiEmailRoute,
  CategorySlugRoute: CategorySlugRoute,
  PayMethodRoute: PayMethodRoute,
  ProductIdRoute: ProductIdRoute,
  ShopIdRoute: ShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
