/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComoPagarRouteImport } from './routes/como-pagar'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as JustinaRouteImport } from './routes/justina'
import { Route as MeRouteImport } from './routes/me'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PointsRouteImport } from './routes/points'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SuperOfertasRouteImport } from './routes/super-ofertas'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TrocasDevolucoesRouteImport } from './routes/trocas-devolucoes'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiEmailRouteImport } from './routes/api/email'
import { Route as ApiSignupVerificationRouteImport } from './routes/api/signup-verification'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as JustinaIndexRouteImport } from './routes/justina.index'
import { Route as JustinaCategoriasRouteImport } from './routes/justina.categorias'
import { Route as JustinaConfigRouteImport } from './routes/justina.config'
import { Route as JustinaCuponsRouteImport } from './routes/justina.cupons'
import { Route as JustinaEquipaRouteImport } from './routes/justina.equipa'
import { Route as JustinaHomeRouteImport } from './routes/justina.home'
import { Route as JustinaLogisticaRouteImport } from './routes/justina.logistica'
import { Route as JustinaLojasRouteImport } from './routes/justina.lojas'
import { Route as JustinaMetasRouteImport } from './routes/justina.metas'
import { Route as JustinaPagamentosRouteImport } from './routes/justina.pagamentos'
import { Route as JustinaPedidosRouteImport } from './routes/justina.pedidos'
import { Route as JustinaPesquisasRouteImport } from './routes/justina.pesquisas'
import { Route as JustinaProdutosRouteImport } from './routes/justina.produtos'
import { Route as JustinaReceitaRouteImport } from './routes/justina.receita'
import { Route as JustinaUsuariosRouteImport } from './routes/justina.usuarios'
import { Route as PayMethodRouteImport } from './routes/pay.$method'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as JustinaAbasIdRouteImport } from './routes/justina.abas.$id'
import { Route as JustinaLojasIdRouteImport } from './routes/justina.lojas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoPagarRoute = ComoPagarRouteImport.update({
  id: '/como-pagar',
  path: '/como-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const JustinaRoute = JustinaRouteImport.update({
  id: '/justina',
  path: '/justina',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperOfertasRoute = SuperOfertasRouteImport.update({
  id: '/super-ofertas',
  path: '/super-ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasDevolucoesRoute = TrocasDevolucoesRouteImport.update({
  id: '/trocas-devolucoes',
  path: '/trocas-devolucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailRoute = ApiEmailRouteImport.update({
  id: '/api/email',
  path: '/api/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignupVerificationRoute = ApiSignupVerificationRouteImport.update({
  id: '/api/signup-verification',
  path: '/api/signup-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JustinaIndexRoute = JustinaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaCategoriasRoute = JustinaCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaConfigRoute = JustinaConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaCuponsRoute = JustinaCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaEquipaRoute = JustinaEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaHomeRoute = JustinaHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaLogisticaRoute = JustinaLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaLojasRoute = JustinaLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaMetasRoute = JustinaMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaPagamentosRoute = JustinaPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaPedidosRoute = JustinaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaPesquisasRoute = JustinaPesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaProdutosRoute = JustinaProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaReceitaRoute = JustinaReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaUsuariosRoute = JustinaUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => JustinaRoute,
} as any)
const PayMethodRoute = PayMethodRouteImport.update({
  id: '/pay/$method',
  path: '/pay/$method',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JustinaAbasIdRoute = JustinaAbasIdRouteImport.update({
  id: '/abas/$id',
  path: '/abas/$id',
  getParentRoute: () => JustinaRoute,
} as any)
const JustinaLojasIdRoute = JustinaLojasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JustinaLojasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/como-pagar': typeof ComoPagarRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/justina': typeof JustinaRouteWithChildren
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/super-ofertas': typeof SuperOfertasRoute
  '/support': typeof SupportRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/wallet': typeof WalletRoute
  '/api/email': typeof ApiEmailRoute
  '/api/signup-verification': typeof ApiSignupVerificationRoute
  '/category/$slug': typeof CategorySlugRoute
  '/justina/categorias': typeof JustinaCategoriasRoute
  '/justina/config': typeof JustinaConfigRoute
  '/justina/cupons': typeof JustinaCuponsRoute
  '/justina/equipa': typeof JustinaEquipaRoute
  '/justina/home': typeof JustinaHomeRoute
  '/justina/logistica': typeof JustinaLogisticaRoute
  '/justina/lojas': typeof JustinaLojasRouteWithChildren
  '/justina/metas': typeof JustinaMetasRoute
  '/justina/pagamentos': typeof JustinaPagamentosRoute
  '/justina/pedidos': typeof JustinaPedidosRoute
  '/justina/pesquisas': typeof JustinaPesquisasRoute
  '/justina/produtos': typeof JustinaProdutosRoute
  '/justina/receita': typeof JustinaReceitaRoute
  '/justina/usuarios': typeof JustinaUsuariosRoute
  '/pay/$method': typeof PayMethodRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/justina/': typeof JustinaIndexRoute
  '/justina/abas/$id': typeof JustinaAbasIdRoute
  '/justina/lojas/$id': typeof JustinaLojasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/como-pagar': typeof ComoPagarRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/super-ofertas': typeof SuperOfertasRoute
  '/support': typeof SupportRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/wallet': typeof WalletRoute
  '/api/email': typeof ApiEmailRoute
  '/api/signup-verification': typeof ApiSignupVerificationRoute
  '/category/$slug': typeof CategorySlugRoute
  '/justina/categorias': typeof JustinaCategoriasRoute
  '/justina/config': typeof JustinaConfigRoute
  '/justina/cupons': typeof JustinaCuponsRoute
  '/justina/equipa': typeof JustinaEquipaRoute
  '/justina/home': typeof JustinaHomeRoute
  '/justina/logistica': typeof JustinaLogisticaRoute
  '/justina/lojas': typeof JustinaLojasRouteWithChildren
  '/justina/metas': typeof JustinaMetasRoute
  '/justina/pagamentos': typeof JustinaPagamentosRoute
  '/justina/pedidos': typeof JustinaPedidosRoute
  '/justina/pesquisas': typeof JustinaPesquisasRoute
  '/justina/produtos': typeof JustinaProdutosRoute
  '/justina/receita': typeof JustinaReceitaRoute
  '/justina/usuarios': typeof JustinaUsuariosRoute
  '/pay/$method': typeof PayMethodRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/justina': typeof JustinaIndexRoute
  '/justina/abas/$id': typeof JustinaAbasIdRoute
  '/justina/lojas/$id': typeof JustinaLojasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/como-pagar': typeof ComoPagarRoute
  '/coupons': typeof CouponsRoute
  '/favorites': typeof FavoritesRoute
  '/justina': typeof JustinaRouteWithChildren
  '/me': typeof MeRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/points': typeof PointsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/super-ofertas': typeof SuperOfertasRoute
  '/support': typeof SupportRoute
  '/termos': typeof TermosRoute
  '/trocas-devolucoes': typeof TrocasDevolucoesRoute
  '/wallet': typeof WalletRoute
  '/api/email': typeof ApiEmailRoute
  '/api/signup-verification': typeof ApiSignupVerificationRoute
  '/category/$slug': typeof CategorySlugRoute
  '/justina/categorias': typeof JustinaCategoriasRoute
  '/justina/config': typeof JustinaConfigRoute
  '/justina/cupons': typeof JustinaCuponsRoute
  '/justina/equipa': typeof JustinaEquipaRoute
  '/justina/home': typeof JustinaHomeRoute
  '/justina/logistica': typeof JustinaLogisticaRoute
  '/justina/lojas': typeof JustinaLojasRouteWithChildren
  '/justina/metas': typeof JustinaMetasRoute
  '/justina/pagamentos': typeof JustinaPagamentosRoute
  '/justina/pedidos': typeof JustinaPedidosRoute
  '/justina/pesquisas': typeof JustinaPesquisasRoute
  '/justina/produtos': typeof JustinaProdutosRoute
  '/justina/receita': typeof JustinaReceitaRoute
  '/justina/usuarios': typeof JustinaUsuariosRoute
  '/pay/$method': typeof PayMethodRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
  '/justina/': typeof JustinaIndexRoute
  '/justina/abas/$id': typeof JustinaAbasIdRoute
  '/justina/lojas/$id': typeof JustinaLojasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/como-pagar'
    | '/coupons'
    | '/favorites'
    | '/justina'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/points'
    | '/privacidade'
    | '/settings'
    | '/store'
    | '/super-ofertas'
    | '/support'
    | '/termos'
    | '/trocas-devolucoes'
    | '/wallet'
    | '/api/email'
    | '/api/signup-verification'
    | '/category/$slug'
    | '/justina/categorias'
    | '/justina/config'
    | '/justina/cupons'
    | '/justina/equipa'
    | '/justina/home'
    | '/justina/logistica'
    | '/justina/lojas'
    | '/justina/metas'
    | '/justina/pagamentos'
    | '/justina/pedidos'
    | '/justina/pesquisas'
    | '/justina/produtos'
    | '/justina/receita'
    | '/justina/usuarios'
    | '/pay/$method'
    | '/product/$id'
    | '/shop/$id'
    | '/justina/'
    | '/justina/abas/$id'
    | '/justina/lojas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/como-pagar'
    | '/coupons'
    | '/favorites'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/points'
    | '/privacidade'
    | '/settings'
    | '/store'
    | '/super-ofertas'
    | '/support'
    | '/termos'
    | '/trocas-devolucoes'
    | '/wallet'
    | '/api/email'
    | '/api/signup-verification'
    | '/category/$slug'
    | '/justina/categorias'
    | '/justina/config'
    | '/justina/cupons'
    | '/justina/equipa'
    | '/justina/home'
    | '/justina/logistica'
    | '/justina/lojas'
    | '/justina/metas'
    | '/justina/pagamentos'
    | '/justina/pedidos'
    | '/justina/pesquisas'
    | '/justina/produtos'
    | '/justina/receita'
    | '/justina/usuarios'
    | '/pay/$method'
    | '/product/$id'
    | '/shop/$id'
    | '/justina'
    | '/justina/abas/$id'
    | '/justina/lojas/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/como-pagar'
    | '/coupons'
    | '/favorites'
    | '/justina'
    | '/me'
    | '/notifications'
    | '/orders'
    | '/points'
    | '/privacidade'
    | '/settings'
    | '/store'
    | '/super-ofertas'
    | '/support'
    | '/termos'
    | '/trocas-devolucoes'
    | '/wallet'
    | '/api/email'
    | '/api/signup-verification'
    | '/category/$slug'
    | '/justina/categorias'
    | '/justina/config'
    | '/justina/cupons'
    | '/justina/equipa'
    | '/justina/home'
    | '/justina/logistica'
    | '/justina/lojas'
    | '/justina/metas'
    | '/justina/pagamentos'
    | '/justina/pedidos'
    | '/justina/pesquisas'
    | '/justina/produtos'
    | '/justina/receita'
    | '/justina/usuarios'
    | '/pay/$method'
    | '/product/$id'
    | '/shop/$id'
    | '/justina/'
    | '/justina/abas/$id'
    | '/justina/lojas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ComoPagarRoute: typeof ComoPagarRoute
  CouponsRoute: typeof CouponsRoute
  FavoritesRoute: typeof FavoritesRoute
  JustinaRoute: typeof JustinaRouteWithChildren
  MeRoute: typeof MeRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PointsRoute: typeof PointsRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRoute
  SuperOfertasRoute: typeof SuperOfertasRoute
  SupportRoute: typeof SupportRoute
  TermosRoute: typeof TermosRoute
  TrocasDevolucoesRoute: typeof TrocasDevolucoesRoute
  WalletRoute: typeof WalletRoute
  ApiEmailRoute: typeof ApiEmailRoute
  ApiSignupVerificationRoute: typeof ApiSignupVerificationRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PayMethodRoute: typeof PayMethodRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopIdRoute: typeof ShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-pagar': {
      id: '/como-pagar'
      path: '/como-pagar'
      fullPath: '/como-pagar'
      preLoaderRoute: typeof ComoPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justina': {
      id: '/justina'
      path: '/justina'
      fullPath: '/justina'
      preLoaderRoute: typeof JustinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-ofertas': {
      id: '/super-ofertas'
      path: '/super-ofertas'
      fullPath: '/super-ofertas'
      preLoaderRoute: typeof SuperOfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas-devolucoes': {
      id: '/trocas-devolucoes'
      path: '/trocas-devolucoes'
      fullPath: '/trocas-devolucoes'
      preLoaderRoute: typeof TrocasDevolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email': {
      id: '/api/email'
      path: '/api/email'
      fullPath: '/api/email'
      preLoaderRoute: typeof ApiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signup-verification': {
      id: '/api/signup-verification'
      path: '/api/signup-verification'
      fullPath: '/api/signup-verification'
      preLoaderRoute: typeof ApiSignupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justina/': {
      id: '/justina/'
      path: '/'
      fullPath: '/justina/'
      preLoaderRoute: typeof JustinaIndexRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/categorias': {
      id: '/justina/categorias'
      path: '/categorias'
      fullPath: '/justina/categorias'
      preLoaderRoute: typeof JustinaCategoriasRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/config': {
      id: '/justina/config'
      path: '/config'
      fullPath: '/justina/config'
      preLoaderRoute: typeof JustinaConfigRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/cupons': {
      id: '/justina/cupons'
      path: '/cupons'
      fullPath: '/justina/cupons'
      preLoaderRoute: typeof JustinaCuponsRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/equipa': {
      id: '/justina/equipa'
      path: '/equipa'
      fullPath: '/justina/equipa'
      preLoaderRoute: typeof JustinaEquipaRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/home': {
      id: '/justina/home'
      path: '/home'
      fullPath: '/justina/home'
      preLoaderRoute: typeof JustinaHomeRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/logistica': {
      id: '/justina/logistica'
      path: '/logistica'
      fullPath: '/justina/logistica'
      preLoaderRoute: typeof JustinaLogisticaRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/lojas': {
      id: '/justina/lojas'
      path: '/lojas'
      fullPath: '/justina/lojas'
      preLoaderRoute: typeof JustinaLojasRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/metas': {
      id: '/justina/metas'
      path: '/metas'
      fullPath: '/justina/metas'
      preLoaderRoute: typeof JustinaMetasRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/pagamentos': {
      id: '/justina/pagamentos'
      path: '/pagamentos'
      fullPath: '/justina/pagamentos'
      preLoaderRoute: typeof JustinaPagamentosRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/pedidos': {
      id: '/justina/pedidos'
      path: '/pedidos'
      fullPath: '/justina/pedidos'
      preLoaderRoute: typeof JustinaPedidosRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/pesquisas': {
      id: '/justina/pesquisas'
      path: '/pesquisas'
      fullPath: '/justina/pesquisas'
      preLoaderRoute: typeof JustinaPesquisasRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/produtos': {
      id: '/justina/produtos'
      path: '/produtos'
      fullPath: '/justina/produtos'
      preLoaderRoute: typeof JustinaProdutosRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/receita': {
      id: '/justina/receita'
      path: '/receita'
      fullPath: '/justina/receita'
      preLoaderRoute: typeof JustinaReceitaRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/usuarios': {
      id: '/justina/usuarios'
      path: '/usuarios'
      fullPath: '/justina/usuarios'
      preLoaderRoute: typeof JustinaUsuariosRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/pay/$method': {
      id: '/pay/$method'
      path: '/pay/$method'
      fullPath: '/pay/$method'
      preLoaderRoute: typeof PayMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/justina/abas/$id': {
      id: '/justina/abas/$id'
      path: '/abas/$id'
      fullPath: '/justina/abas/$id'
      preLoaderRoute: typeof JustinaAbasIdRouteImport
      parentRoute: typeof JustinaRoute
    }
    '/justina/lojas/$id': {
      id: '/justina/lojas/$id'
      path: '/$id'
      fullPath: '/justina/lojas/$id'
      preLoaderRoute: typeof JustinaLojasIdRouteImport
      parentRoute: typeof JustinaLojasRoute
    }
  }
}

interface JustinaLojasRouteChildren {
  JustinaLojasIdRoute: typeof JustinaLojasIdRoute
}

const JustinaLojasRouteChildren: JustinaLojasRouteChildren = {
  JustinaLojasIdRoute: JustinaLojasIdRoute,
}

const JustinaLojasRouteWithChildren = JustinaLojasRoute._addFileChildren(
  JustinaLojasRouteChildren,
)

interface JustinaRouteChildren {
  JustinaCategoriasRoute: typeof JustinaCategoriasRoute
  JustinaConfigRoute: typeof JustinaConfigRoute
  JustinaCuponsRoute: typeof JustinaCuponsRoute
  JustinaEquipaRoute: typeof JustinaEquipaRoute
  JustinaHomeRoute: typeof JustinaHomeRoute
  JustinaLogisticaRoute: typeof JustinaLogisticaRoute
  JustinaLojasRoute: typeof JustinaLojasRouteWithChildren
  JustinaMetasRoute: typeof JustinaMetasRoute
  JustinaPagamentosRoute: typeof JustinaPagamentosRoute
  JustinaPedidosRoute: typeof JustinaPedidosRoute
  JustinaPesquisasRoute: typeof JustinaPesquisasRoute
  JustinaProdutosRoute: typeof JustinaProdutosRoute
  JustinaReceitaRoute: typeof JustinaReceitaRoute
  JustinaUsuariosRoute: typeof JustinaUsuariosRoute
  JustinaIndexRoute: typeof JustinaIndexRoute
  JustinaAbasIdRoute: typeof JustinaAbasIdRoute
}

const JustinaRouteChildren: JustinaRouteChildren = {
  JustinaCategoriasRoute: JustinaCategoriasRoute,
  JustinaConfigRoute: JustinaConfigRoute,
  JustinaCuponsRoute: JustinaCuponsRoute,
  JustinaEquipaRoute: JustinaEquipaRoute,
  JustinaHomeRoute: JustinaHomeRoute,
  JustinaLogisticaRoute: JustinaLogisticaRoute,
  JustinaLojasRoute: JustinaLojasRouteWithChildren,
  JustinaMetasRoute: JustinaMetasRoute,
  JustinaPagamentosRoute: JustinaPagamentosRoute,
  JustinaPedidosRoute: JustinaPedidosRoute,
  JustinaPesquisasRoute: JustinaPesquisasRoute,
  JustinaProdutosRoute: JustinaProdutosRoute,
  JustinaReceitaRoute: JustinaReceitaRoute,
  JustinaUsuariosRoute: JustinaUsuariosRoute,
  JustinaIndexRoute: JustinaIndexRoute,
  JustinaAbasIdRoute: JustinaAbasIdRoute,
}

const JustinaRouteWithChildren =
  JustinaRoute._addFileChildren(JustinaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ComoPagarRoute: ComoPagarRoute,
  CouponsRoute: CouponsRoute,
  FavoritesRoute: FavoritesRoute,
  JustinaRoute: JustinaRouteWithChildren,
  MeRoute: MeRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PointsRoute: PointsRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRoute,
  SuperOfertasRoute: SuperOfertasRoute,
  SupportRoute: SupportRoute,
  TermosRoute: TermosRoute,
  TrocasDevolucoesRoute: TrocasDevolucoesRoute,
  WalletRoute: WalletRoute,
  ApiEmailRoute: ApiEmailRoute,
  ApiSignupVerificationRoute: ApiSignupVerificationRoute,
  CategorySlugRoute: CategorySlugRoute,
  PayMethodRoute: PayMethodRoute,
  ProductIdRoute: ProductIdRoute,
  ShopIdRoute: ShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
